// Auto-generated code. Do not edit.
namespace myImages {

    helpers._registerFactory("image", function(name: string) {
        switch(helpers.stringTrim(name)) {
            case "image1":
            case "Princesa frente":return img`
.....ff44ff.........
....f545545f........
...fe455554ef.......
..fb3e4444e3bf......
..f3333333333f......
.f33eb3ee3be33f.....
.f33ffeeeeff33f.....
.fbbfbfeefbfbbf.....
.fbbe1f44f1ebbf.....
ffbbf444444fbbff....
fbbfffeeeefffbbf....
.feefbddddbfeef.....
..e4cddddddc4e......
..efbdbdbdbbfe......
...ff1d1d1dff.......
.....ffbbff.........
....................
....................
....................
....................
`;
            case "image2":
            case "Grego frente":return img`
..555..55555.5......
..555555555555......
..55dddddddd55......
..5dddddddddd5......
..dd17dddd71dd......
.ddd17dddd71ddd.....
.dddddddddddddd.....
..ddd333333ddd......
...ddd3333ddd.......
....dddddddd.....ff.
......dddd......fff.
...9999999999..fff..
...9999999999.bff...
...9999999999.bb....
...dd999999ddb......
.....999999.........
.....888888.........
.....888888.........
.....88..88.........
.....ff..ff.........
`;
            case "image3":
            case "Troiano frente":return img`
..ffff...fff.f......
..ffffffffffff......
..ffddddddddff......
..fddddddddddf......
..dd1edddde1dd......
.ddd1edddde1ddd.....
.dddddddddddddd.....
..ddd333333ddd......
...ddd3333ddd.......
....dddddddd........
......dddd..........
...2222222222.......
...2222222222.......
...2222222222.......
...dd222222dd.......
.....222222.........
.....eeeeee.........
.....eeeeee.........
.....ee..ee.........
.....ff..ff.........
`;
            case "image4":
            case "Ulisses frente":return img`
....................
....................
....................
....................
....................
....................
....................
....................
....................
....................
....................
....................
....................
....................
....................
....................
....................
....................
....................
....................
`;
        }
        return null;
    })

    helpers._registerFactory("animation", function(name: string) {
        switch(helpers.stringTrim(name)) {

        }
        return null;
    })

    helpers._registerFactory("song", function(name: string) {
        switch(helpers.stringTrim(name)) {

        }
        return null;
    })

    helpers._registerFactory("json", function(name: string) {
        switch(helpers.stringTrim(name)) {

        }
        return null;
    })

}
// Auto-generated code. Do not edit.
